//tealium universal tag - utag.169 ut4.0.202601220330, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.map={};u.extend=[];u.getVID=function(data_layer){return data_layer["cp.utag_main_v_id"]||data_layer["tealium_visitor_id"]||data_layer["ut.visitor_id"];};u.checkVID=function(data_layer,oncePerSession){var vid=u.getVID(data_layer);if(!vid){utag.DB(u.id+": Tag not fired: Visitor ID is undefined");return false;}
if(oncePerSession){if(utag.loader.RC("utag_main")["tag_session_169"]){utag.DB(u.id+": Tag not fired: Same session is detected");return false;}else{utag.loader.SC("utag_main",{"tag_session_169":"1;exp-session"});}}
return true;};u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){if(!u.checkVID(b,true))return;utag.DB("send:169");utag.DB(b);var c,d,e,f,g;u.data={"qsp_delim":"&","kvp_delim":"=","base_url_req_ttdid":"//match.adsrvr.org/track/cmf/generic?","base_url_get_ttdid":"//datacloud.tealiumiq.com/tealium_ttd/main/16/i.js?jsonp=utag.ut.tealium_pass_ttdid","base_url_pass_ttdid":"//datacloud.tealiumiq.com/vdata/i.gif?","tealium_account":"unimelb","tealium_profile":"main","ttd_pid":"tealium","ttd_tpi":"1","gdpr":"0","gdpr_consent":"","delay":5000,"interval":0,"sin":4,"iab_v20_compliance":true,"domain":''};utag.DB("send:169:EXTENSIONS");utag.DB(b);c=[];g=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
utag.DB("send:169:MAPPINGS");utag.DB(u.data);if(b["cp.utag_main_cms_169"]){utag.DB("Same session detected; duplicate The TradeDesk Cookie Matching Service call not sent.");return;}
if(u.data.iab_v20_compliance===true||u.data.iab_v20_compliance==="true"){if(typeof __tcfapi==="function"){__tcfapi("getTCData",2,function(tcData,success){if(success){u.data.tc_string+="gdpr=";if(tcData.gdprApplies===true){u.data.gdpr="1";}else if(tcData.gdprApplies===false){u.data.gdpr="0";}else{u.data.gdpr=String(tcData.gdprApplies);}
u.data.gdpr_consent=tcData.tcString;execute_send();}});}else{var frame=window;var cmpFrame;var cmpCallbacks={};while(frame){try{if(frame.frames["__tcfapiLocator"]){cmpFrame=frame;break;}}catch(error){utag.DB(error);}
if(frame===window.top){break;}
frame=frame.parent;}
if(!cmpFrame){execute_send();}else{window.__tcfapi=function(cmd,version,callback,arg){var callId=String(Math.random());var msg={__tcfapiCall:{command:cmd,parameter:arg,version:version,callId:callId}};cmpCallbacks[callId]=callback;cmpFrame.postMessage(msg,"*");};window.tealiumiabPostMessageHandler=function(event){var json={};try{json=typeof event.data==="string"?JSON.parse(event.data):event.data;}catch(error){utag.DB(error);}
var payload=json.__tcfapiReturn;if(payload){if(typeof cmpCallbacks[payload.callId]==="function"){cmpCallbacks[payload.callId](payload.returnValue,payload.success);cmpCallbacks[payload.callId]=null;}}};window.addEventListener("message",tealiumiabPostMessageHandler,false);__tcfapi("getTCData",2,function(tcData,success){if(success){u.data.tc_string+="gdpr=";if(tcData.gdprApplies===true){u.data.gdpr="1";}else if(tcData.gdprApplies===false){u.data.gdpr="0";}else{u.data.gdpr=String(tcData.gdprApplies);}
u.data.gdpr_consent=tcData.tcString;execute_send();}});}}}else{execute_send();}
function execute_send(){u.data.tealium_account=u.data.tealium_account||utag.cfg.utid.split("/")[0];u.data.tealium_profile=u.data.tealium_profile||utag.cfg.utid.split("/")[1];u.data.order_id=u.data.order_id||b._corder||"";if(!b["cp.utag_main_ttd_uuid"]&&!u.data.order_id){c.push("ttd_pid"+u.data.kvp_delim+u.data.ttd_pid);c.push("ttd_tpi"+u.data.kvp_delim+u.data.ttd_tpi);c.push("gdpr"+u.data.kvp_delim+u.data.gdpr);if(u.data.gdpr==="1"&&u.typeOf(u.data.gdpr_consent)==="string"&&u.data.gdpr_consent!==""){c.push("gdpr_consent"+u.data.kvp_delim+u.data.gdpr_consent);}
u.data.domain=u.data.domain||b['ut.domain'];c.push("domain"+u.data.kvp_delim+u.data.domain);u.loader({"type":"img","src":u.data.base_url_req_ttdid+c.join(u.data.qsp_delim)});utag.ut.tealium_pass_ttdid=function(o){try{var tl=o.tvt?o.tvt.length:0;if(tl!=0){utag.loader.SC("utag_main",{"ttd_uuid":(o.tvt[tl-1].t1+";exp-session")});u.data.domain=u.data.domain||b['ut.domain'];g.push("gdpr"+u.data.kvp_delim+u.data.gdpr);if(u.data.gdpr==="1"&&u.typeOf(u.data.gdpr_consent)==="string"&&u.data.gdpr_consent!==""){g.push("gdpr_consent"+u.data.kvp_delim+u.data.gdpr_consent);}
g.push("ttd_uuid"+u.data.kvp_delim+o.tvt[tl-1].t1);g.push("tealium_vid"+u.data.kvp_delim+u.getVID(b));g.push("tealium_account"+u.data.kvp_delim+u.data.tealium_account);g.push("tealium_profile"+u.data.kvp_delim+u.data.tealium_profile);g.push("tealium_cookie_sync"+u.data.kvp_delim+"true");g.push("domain"+u.data.kvp_delim+u.data.domain);if(b.tealium_trace_id){g.push("tealium_trace_id"+u.data.kvp_delim+b.tealium_trace_id);}
utag.loader.SC("utag_main",{"cms_169":"1;exp-session"});u.loader({"type":"img","src":u.data.base_url_pass_ttdid+g.join(u.data.qsp_delim)});clearInterval(u.polling_interval);}}catch(e){utag.DB(e);}}
u.get_ttdid=function(interval,sin){if(interval>=sin){clearInterval(u.polling_interval);}else{u.loader({"type":"script","src":u.data.base_url_get_ttdid,"cb":null,"loc":"script","id":"utag_169_get_ttdid","attrs":{}});u.data.interval++;}}
u.polling_interval=setInterval(function(){u.get_ttdid(u.data.interval,u.data.sin);},u.data.delay);}
utag.DB("send:169:COMPLETE");}}};utag.o[loader].loader.LOAD(id);}("169","unimelb.main"));}catch(error){utag.DB(error);}
